FORMAT: 1A
HOST: https://apx-graphs.e-com.plus/api/v1/

# E-Com Plus Graphs API

[E-Com Plus](https://www.e-com.plus)
is a robust and flexible cloud commerce software,
totally based on REST APIs, providing a large library of methods and specifications
to deploy any digital commerce operation easly

**Graphs API** is our public REST interface to
[Neo4j](https://neo4j.com/) (graph database),
our real-time recommendation engine, used to better implementations of
products recommendations systems
