+ Parameters
    + _id: a00000000000000000000000 (string, required) - The product ID

+ Response 200 (application/json)

        {
          "results": [
            {
              "columns": [
                "products.id"
              ],
              "data": [
                {
                  "row": [
                    "a00000000000000000000011"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000012"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000013"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000014"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000015"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000016"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000017"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000018"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000019"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a0000000000000000000001a"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a0000000000000000000001b"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a0000000000000000000001c"
                  ],
                  "meta": [
                    null
                  ]
                }
              ]
            }
          ],
          "errors": []
        }
