+ Parameters
    + _id: a00000000000000000000000 (string, required) - The product ID

+ Response 200 (application/json)

        {
          "results": [
            {
              "columns": [
                "products.id"
              ],
              "data": [
                {
                  "row": [
                    "a00000000000000000000001"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000002"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000003"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000004"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000005"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000006"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000007"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000008"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a00000000000000000000009"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a0000000000000000000000a"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a0000000000000000000000b"
                  ],
                  "meta": [
                    null
                  ]
                },
                {
                  "row": [
                    "a0000000000000000000000c"
                  ],
                  "meta": [
                    null
                  ]
                }
              ]
            }
          ],
          "errors": []
        }
